if("undefined"==typeof jQuery){var newScript=document.createElement("script");newScript.src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js";newScript.type="text/javascript";var docHead=document.getElementsByTagName("head")[0],firstScript=document.getElementsByTagName("script")[0];docHead.insertBefore(newScript,firstScript);newScript.readyState?newScript.onreadystatechange=function(){("loaded"==newScript.readyState||"complete"==newScript.readyState)&&loadDTK(jQuery,window,document)}:
newScript.onload=function(){loadDTK(jQuery,window,document)}}else loadDTK(jQuery,window,document);
function loadDTK(b,g,d,k){function q(a,l){function e(a){if("reverse"===a)var l=!0;if(l)for(a=d-1;-1<a;a--)b(c[a]).hasClass("currentPic")&&(j=c[a],k=h[a],0==a?(i=c[d-1],n=h[d-1]):(i=c[a-1],n=h[a-1]));else if(g)for(a=0;a<d;a++)b(c[a]).hasClass("currentPic")&&(j=c[a],k=h[a],a+1==d?(i=c[0],n=h[0]):(i=c[a+1],n=h[a+1]));else for(a=0;a<d;a++)b(c[a]).hasClass("currentPic")&&(j=c[a],i=a+1==d?c[0]:c[a+1]);if(m.options.carousel){var f=b(j).width();b(j).removeClass("currentPic");l?(b(i).addClass("currentPic").css({left:-f,
display:"block"}),b(j).animate({left:f},400,function(){b(this).css({display:"none",left:f})})):(b(i).addClass("currentPic").css({right:-f,display:"block",left:f}),b(j).animate({left:-f},400,function(){b(this).css({display:"none",left:f})}));b(i).animate({left:0,right:0})}else b(j).removeClass("currentPic"),b(i).addClass("currentPic"),b(i).fadeIn(1E3,function(){b(j).hide()});b(k).removeClass("selected");b(n).addClass("selected")}var c=b(a).find(".slide"),h=b(a).find("#btns a"),f=b("#content").find(".forward_btn"),
d=c.length,g=h.length,j=b(a).find(".currentPic"),k,i,n;this.options=b.extend({},{speed:4E3,carousel:!1},l);var m=this;this.intervalID=null;if(f){var f=b("#content").find(".forward_btn"),p=b("#content").find(".back_btn");f.length&&f.click(function(){e();return!1});p.length&&p.click(function(){e("reverse");return!1})}g&&b(h).click(function(a){a.stopPropagation();c.each(function(a){b(c[a]).hide().removeClass("currentPic");b(h[a]).removeClass("selected")});a=b(this).index();b(c[a]).fadeIn().addClass("currentPic");
b(h[a]).addClass("selected");clearInterval(m.intervalID);return!1});b(a).mouseleave(function(){clearInterval(m.intervalID);m.intervalID=setInterval(e,m.options.speed)}).mouseenter(function(){clearInterval(m.intervalID)});this.intervalID=setInterval(e,this.options.speed)}g.DTK={addWindowLoadEvent:function(a){return a?(g.addEventListener?g.addEventListener("load",a,!1):g.attachEvent("onload",a),this):!1},removeBreadcrumb:function(){var a=d.getElementById("content_area").getElementsByTagName("table")[0];
a.parentNode.removeChild(a);return this},removeAllTablePadding:function(){for(var a=d.getElementsByTagName("table"),b=a.length,e=0;e<b;e++)a[e].setAttribute("cellpadding","0"),a[e].setAttribute("cellspacing","0");return this},injectTag:function(a){var b={type:null,url:null,callback:null,node:"script",cache:!0},e;for(e in b)"undefined"==typeof a[e]&&(a[e]=b[e]);b=d.getElementsByTagName(a.node)[0];if("stylesheet"==a.type)return b=b.parentNode,d.createStyleSheet?d.createStyleSheet(a.url):(cssTag=d.createElement("link"),
cssTag.setAttribute("rel","stylesheet"),cssTag.setAttribute("type","text/css"),cssTag.setAttribute("href",a.url),b.appendChild(cssTag)),this;if("script"==a.type){var c=d.createElement("script");c.type="text/javascript";ts=(new Date).getTime();c.readyState?c.onreadystatechange=function(){if("loaded"==c.readyState||"complete"==c.readyState)c.onreadystatechange=null,"function"==typeof a.callback&&a.callback()}:c.onload=function(){"function"==typeof a.callback&&a.callback()};!1==a.cache&&(a.url+=(/\?/.test(a.url)?
"&":"?")+"vjsNoCache="+ts);c.src=a.url;b.parentNode.insertBefore(c,b);return this}},checkPage:function(a){if("function"==typeof PageName){if(PageName().split("#")[0]==a.toLowerCase())return!0;if("default.asp"==a.toLowerCase())return""==PageName().split("#")[0]?!0:!1}},loadCSS:function(a){if(a){if(this.checkPage("searchresults.asp"))var b="/v/vspfiles/templates/"+a+"/css/category.css";this.checkPage("productdetails.asp")&&(b="/v/vspfiles/templates/"+a+"/css/productdetails.css");this.checkPage("shoppingcart.asp")&&
(b="/v/vspfiles/templates/"+a+"/css/shoppingcart.css");this.checkPage("one-page-checkout.asp")&&(b="/v/vspfiles/templates/"+a+"/css/onepagecheckout.css");this.checkPage("orderfinished.asp")&&(b="/v/vspfiles/templates/"+a+"/css/thankyou.css");this.checkPage("dealoftheday.asp")&&(b="/v/vspfiles/templates/"+a+"/css/dealoftheday.css");b&&this.injectTag({type:"stylesheet",url:b});this.injectTag({type:"stylesheet",url:"/v/vspfiles/templates/"+a+"/css/softaddtocart.css"});return this}alert("No template name specified");
return!1},placeholderPolyfill:function(){"placeholder"in d.createElement("input")||b("input[placeholder]").each(function(){var a=b(this).attr("placeholder");b(this).removeAttr("placeholder").val(a);b(this).bind({focus:function(){b(this).val()==a&&b(this).val("")},blur:function(){""==b(this).val()&&b(this).val(a)}})})},formCheck:function(a){var l=g.attachEvent?!0:!1,e=g.WebKitAnimationEvent&&!g.WebGLActiveInfo?!0:!1,a=a.elements,c=0;if("undefined"!=typeof d.body.style.MozBoxShadow||l||e){if(b.each(a,
function(a,b){b.style.outline="";if(b.getAttribute("required")!=k){if(""==b.value||-1==b.selectedIndex)b.hasAttribute==k?b.style.border="1px solid #d30000":b.style.outline="1px solid #d30000",c++}else"email"==b.getAttribute("type")&&!/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(b.value)&&(b.hasAttribute==k?b.style.border="1px solid #d30000":b.style.outline="1px solid #d30000",c++)}),
0<c)return alert("The fields in red are either required or invalid."),!1}else return!0},addYear:function(){var a=(new Date).getFullYear();0<b(".insertYear").length&&b(".insertYear").html(a)},init:function(){this.placeholderPolyfill();this.addYear()}};b(d).ready(function(){DTK.init()});b.fn.vslide=function(a){return this.each(function(){new q(this,a)})}};